version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=cva
      - MYSQL_PASSWORD=4ut3nt1c4R
      - MYSQL_ROOT_PASSWORD=4ut3nt1c4R
      - MYSQL_DATABASE=db_cva

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - "9000:80"
    environment:
      - PMA_ARBITRARY=1

  app:
    build: .
    volumes:
      - .:/var/www/html:z
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "80:80"
    environment:
      - DBHOST=mysql
      - MYSQL_USER=cva
      - MYSQL_PASSWORD=4ut3nt1c4R
      - MYSQL_DATABASE=db_cva