version: "3"

networks:
  banco:
  app:

services:

  mysql:
    image: mysql:5.7
    container_name: sourcess-mysql
    volumes:
      - ./default.sql:/docker-entrypoint-initdb.d/dump.sql
    volumes:
      - database-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - banco
    env_file:
      - ./secrets.env

  app:
    build: ./src
    container_name: sourcess-app
    volumes:
      - ./src:/var/www/html:z
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - banco
      - app
    env_file:
      - ./secrets.env

volumes:
  database-volume: