version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_USER=controle
      - MYSQL_PASSWORD=4ut3nt1c4R
      - MYSQL_ROOT_PASSWORD=4ut3nt1c4R
      - MYSQL_DATABASE=db_controle_acesso

  app:
    build: .
    volumes:
      - .:/var/www/html:z
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      - DBHOST=mysql
      - MYSQL_USER=cva
      - MYSQL_PASSWORD=4ut3nt1c4R
      - MYSQL_DATABASE=db_cva