<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita9f2b5508cc25bb32b2b32ce8f5595ea
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Sourcess\\' => 9,
        ),
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Sourcess\\' => 
        array (
            0 => __DIR__ . '/../..' . '/classes',
        ),
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'Slim' => 
            array (
                0 => __DIR__ . '/..' . '/slim/slim',
            ),
        ),
        'R' => 
        array (
            'Rain' => 
            array (
                0 => __DIR__ . '/..' . '/rain/raintpl/library',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita9f2b5508cc25bb32b2b32ce8f5595ea::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita9f2b5508cc25bb32b2b32ce8f5595ea::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInita9f2b5508cc25bb32b2b32ce8f5595ea::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
